# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HugPosting',
            fields=[
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pair', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_hug', to='hugs.HugPosting')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('hugs', models.IntegerField(default=0)),
                ('rejects', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
