# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hugposting',
            old_name='user',
            new_name='user_origin',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='user_origin',
        ),
        migrations.AddField(
            model_name='hugposting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
