# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugs', '0002_auto_20170204_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hugposting',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_hug', to='hugs.HugPosting'),
        ),
    ]
