# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugs', '0003_auto_20170204_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='hugposting',
            name='pair2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hugs.HugPosting'),
        ),
        migrations.AlterField(
            model_name='hugposting',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_hug', to='hugs.HugPosting'),
        ),
    ]
