# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugs', '0004_auto_20170204_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hugposting',
            name='pair2',
        ),
    ]
