# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugs', '0005_remove_hugposting_pair2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hugposting',
            name='cached_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hugs.HugPosting'),
        ),
    ]
