# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugs', '0006_hugposting_cached_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hugposting',
            name='cached_pair',
        ),
    ]
