# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugs', '0008_hugposting_hugged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hugposting',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='hugposting',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
    ]
